### ISSUE TITLE
text_processing2 두번째문제 질문입니다.

### ISSUE THREAD

**Issue by 1kimtaeyong** [TEAMLAB-Lecture/python-101-for-data-science-by-pknu#14]
# 언더바(_)가 없으면 그대로 사용한다.
    if "_" not in underscore_str:
        return underscore_str
# 언더바(_)가 있으면 공백처리를 한다.
    blank_list = underscore_str.split("_")
    camelcase_str = []
    for blank in blank_list:
        if blank != "":
            camelcase_str.append(blank.capitalize())
    camelcase_str[0] = camelcase_str[0].lower()
    camelcase_str = "".join(camelcase_str)
    return camelcase_str 

![과제](https://user-images.githubusercontent.com/102029177/163184629-193cdb09-b82e-4845-83b0-5112e5b97a6c.png)
안녕하세요 교수님 늦은시간에 죄송합니다.
보기와 같이 언더바가 없으면 그대로 사용하고 있으면 공백처리를 한뒤에
그 뒤에 오는 알파벳을 대문자 시킨 뒤 join 함수를 써서 붙였습니다.
결과는 맞게 나오지만 submit.py에서는 틀렸다고 합니다.
어느부분이 틀린것인지 잘모르겠습니다.

**Comment by blissray** [comment]
예 그건 해결해야 합니다. 요구사항에 적혀있습니다.

**Comment by 1kimtaeyong** [comment]
넵 감사합니다!!
