### ISSUE TITLE
exam_grader에 관한 질문

### ISSUE THREAD

**Issue by 54162476** [TEAMLAB-Lecture/python-101-for-data-science-by-pknu#23]
def get_number_of_subjects():
        number_of_subjects = int(input("과목수를 입력하세요:"))
        return number_of_subjects

    def get_average_score(number_of_subjects,total_score):
        average_score = float(int(total_score) / int(number_of_subjects))
        return average_score

    if __name__ == '__main__':
        print("Start of Exam Grader Program")
        print("============================")
        number_of_subjects = get_number_of_subjects()
        total_score = sum_of_scores(number_of_subjects)
        average_score = get_average_score(number_of_subjects,total_score)     
        print_exam_grader(average_score) 
        print("===========================")
        print("End of Exame Grader Program")

**Comment by blissray** [comment]
```
def get_average_score(number_of_subjects,total_score):
```
함수 파라메터 순서가 틀렸네요
