### ISSUE TITLE
text_processing 1-1 질문드립니다! 

### ISSUE THREAD

**Issue by kominjin** [TEAMLAB-Lecture/python-101-for-data-science-by-pknu#3]
for 문으로 하다가 잘 안 되어서 다른 방법을 찾았는데 틀렸다고 떠서 질문드려요
```
normalized_string= None
input_string1=input()
normalized_string = str(input())
normalized_string = normalized_string.lower()
normalized_string = normalized_string.strip()
normalized_string = normalized_string.split()
normalized_string = (' ', join(normalized_string))
return normalized_string
```
이렇게 소문자로 다 바꾸어주고>양 옆 공백 삭제하고>공백 한 칸 포함해서 다시 묶는걸로 했는데 접근 방식 자체가 틀렸는지 아님 다른게 문제인지 잘 모르겠습니다.

**Comment by blissray** [comment]
아래와 같이 고려하면 좋겠습니다.

본 숙제에서는 사용자의 input 값을 받는 것이 아니라 함수의 파라메터로 input 값을 받기 때문에 아래 코드는 사용되지 않습니다.

```
input_string1=input()
```

더불어 두번의 input을 받을 필요도 없으므로 아래 두줄 코드 필요가 없습니다. 
```
input_string1=input()
normalized_string = str(input())
```

대신 함수의 파라메터를 확인하여 `normalized_string` 과 연결하면 됩니다.

추가적인 질문을 확인후 부탁드립니다.

**Comment by kominjin** [comment]
> 
두가지 질문이 더 있습니다ㅜㅠ
1. input()을 쓰지 않아도 파라미터에 input_?? 형태를 가지면 입력받을 수 있는 건가요?
2. 파라메터를 normalized_string이랑 연결하라고 하셔서 normalized_string = input_string을 normalized_string =None 코드 밑에 작성하였더니 또 Check your grammar이 뜹니다. 혹시 연결하라고 하신 게 다른 의미인가요..?

**Comment by blissray** [comment]
예 먼저 함수 파트를 다시한번 볼 것을 권장드립니다.

아래와 같이 숙제 코드가 있습니다.

```
def normalize(input_string):
    normalized_string = None
    return normalized_string 
```

이 코드를 사용하기 위해서 아래와 같이 코드를 쓸 수 있습니다.
```
input_string1 = "This is an example."
normalize(input_string1)
```

함수의 input 파라메터와 민진님께서 생각하시는 `input` 함수의 역할이 다릅니다. `input` 함수는 말그대로 사용자의 입력을 받는 함수이고, `input` 파라메터는 함수내부에 값을 전달하는 변수입니다. 구분을 하기 위해서 공부를 해보시면 좋겠습니다.

또한 아래 부분 코드가 틀렸습니다. 아직 `join` 함수를 완벽히 이해 못했을 건데 for loop을 사용해서 도전해 보세요.

```
normalized_string = (' ', join(normalized_string))
```

` 코드를 제출하기 전에 꼭 실행시켜보시기 바랍니다.`

**Comment by kominjin** [comment]
교수님 join부분 코드를 책 보고 고쳐서
normalized_string = " ".join(normalized_string)
이렇게 쓰니까  pass가 떴습니다.
그런데 띄워쓰기가 한칸으로되는 건 for loop로 도저히 못 풀겠습니다. ㅜ

**Comment by blissray** [comment]
예 정말고생하셨습니다.
수업시간에 같이해봐요

2022년 4월 8일 (금) 오후 2:24, minjin ***@***.***>님이 작성:

**Comment by kominjin** [comment]
넵!
