### ISSUE TITLE
basic_math 코딩 관련 질문..

### ISSUE THREAD

**Issue by 202211304KJH** [TEAMLAB-Lecture/python-101-for-data-science-by-pknu#4]
badgate가 뜨는 이유가 문법 틀려서라고 하셔서,,
제가 코딩 문법이 어디가 틀렸는지 잘 못 찾겠어서요.
어디가 잘못된건지 힌트 알려주실 수 있나요ㅠ
![캡처](https://user-images.githubusercontent.com/103183655/162175187-36da43ba-ebcd-440a-9694-06fbf56b7413.PNG)

**Comment by blissray** [comment]
먼저 해당 함수의 코드 전체를 이미지 파일이 아닌 코드 형태로 붙여넣기 해주세요.

**Comment by blissray** [comment]
일단 함수 부터 제대로 작성이 필요하고. TA 세션과 이전 codeborn 수업의 내용을 습득 못한거 같습니다.

1. 함수를 제대로 작성해주세요. 현재는 함수형태가 아닙니다.
2. 코드이 identation을 만들어서 붙여주세요. 아래와 같이 markdown 언어로 쓰는 법을 이해하시기 바랍니다. 
   영상 참고 (https://www.youtube.com/watch?v=kMEb_BzyUqk&t=301s)
3.  원래 숙제 코드 형태를 참고하셔서 코드를 작성하시기 바랍니다.

**Comment by 202211304KJH** [comment]
넵! 열심히 공부하겠습니당.

**Comment by 202211304KJH** [comment]
`    greatest_number = None
    
    max_number_list = number_list[0]
    for i in number_list:
        if i>max_number_list:
         max_number_list=number_list
 print("최대값=%d")%(max_number_list))
    return greatest_number`

교수님 이 코딩에서도 잘못된 부분이 있을까요?

**Comment by 202211304KJH** [comment]
`    greatest_number = None
    
    max_number_list = number_list[0]
    for i in number_list:
        if i>max_number_list:
         max_number_list=number_list
 print("최대값=%d")%(max_number_list))
    return greatest_number`

교수님 이 코딩에서도 잘못된 부분이 있나요 ?

**Comment by blissray** [comment]
함수의 파라메터 부분은 어디인가요? 함수 이름을 선언하고 파라메터를 선언한 부분이 있습니다. 그 부분을 같이 붙여넣어야 합니다. 함수에 대한 이해가 부족한 걸로 보이는데 함수 영상은 보셨나요?

**Comment by 202211304KJH** [comment]
죄송합니다. 다시 짜보겠습니다.

**Comment by 202211304KJH** [comment]
`    max_number_list = None
    
    max_number_list = number_list[0]
    for i in number_list:
      if i>max_number_list:
         i = max_number_list
    return max_number_list 
number_list = [39, 54, 32, 11, 99]
print(get_greatest(number_list))`
교수님 다시 짰습니다. 근데 답이 99가 아닌 39가 나옵니다... 이유를 모르겠습니다.

**Comment by 202211304KJH** [comment]
![Uploading 캡처2.PNG…]()

**Comment by blissray** [comment]
1. 일단 코드를 아래처럼 똑바로 붙여넣어 주세요.
```
  max_number_list = None
  
  max_number_list = number_list[0]
  for i in number_list:
    if i>max_number_list:
       i = max_number_list
  return max_number_list 
number_list = [39, 54, 32, 11, 99]
print(get_greatest(number_list))
```

2. i 는 계속 for loop이 돌면서 변하는 값입니다. 근데 i에 해당 값을 할당하니 문제가 생기네요. 반대로 
`max_number_list = i`를 하셔야 하는 거 아닐까요? 종이와 펜을 가지고 한줄 씩 확인해가면서 코딩하면 더 좋은 결과가 있을거 같습니다.
