### ISSUE TITLE
6주차 참고영상 String and Advanced Function 관련질문

### ISSUE THREAD

**Issue by sieuno3o** [TEAMLAB-Lecture/python-101-for-data-science-by-pknu#7]
펑션 내에서 뭔가를 사용 할 때 새롭게 들어온 리스트 값 같은것을 복사 해 주는게 좋다고 말씀 하시면서 사진에 노란색 형광펜 쳐 놓은 부분을 새롭게 적어 주셨는데, 이게 무슨 말인지 이해가 잘 되지 않습니다
복사를 한 뒤 파란색 형광펜을 쳐 놓은 부분을 temp_list로 바꾸어 쓰는게 낫다는 말씀 이신지, 아니면 그냥 저렇게 추가만 해 놓아도 되는건지 궁금합니다 
![image](https://user-images.githubusercontent.com/103474525/162868363-947e7361-9c67-49bd-87be-d213c5980df9.png)

**Comment by blissray** [comment]
예 가능하면 코드를 직접 붙여주시면 좋겠습니다. 그림으로 붙이면 나중에 해석이 안됩니다.

1. 해당 기법은 일반적으로  함수에서 파라메터로 받은 값들을 단순히 변경하게 되면 함수 밖에서의 변경도 함께 일어납니다.
2. 우리 수업 강의자료에서는 spam과 egg 리스트가 비슷한 경우라고 볼 수 있습니다.
3. 그런 의도치 않은 변경을 위해서 보통 리스트 값등을 파라메터로 받을 경우 해당 리스트 값을 복사하여 사용하는 것이 값의 변경에서 자유롭다는 의미라고 보실 수 있습니다.

좋은 질문 감사드립니다.

**Comment by sieuno3o** [comment]
넵 주의하겠습니다.

예를 들어 파라메터로 받은 `list[1,2,3,4]`를 함수 내에서 `a_list = list[:]`로 복사 한 뒤 `a_list`를 사용하여 함수를 작성하는 것이 값의 변경에서 자유로우니 권장한다는 말씀이실까요? 제가 잘 이해한건지 궁금합니다.

**Comment by blissray** [comment]
예 맞습니다. 잘못할 경우 함수밖에 있는 list의 원래 값이 변경 될 수 있어 의도치 않은 변경이 발생할 수 있습니다.

**Comment by sieuno3o** [comment]
네 이해 했습니다. 감사합니다!
